server:
  port: 9100

spring:
  application:
    name: aws-test-back

  # profiles 설정
  # TODO : 다른 방법 알아보기
#  profiles:
#    include:
#    - aws
#    - credentials

  # embedded ??
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    #h2
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:testdb
    #    username: sa

    # mysql-aws
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.ip}:3306/awstest?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${db.id}
    password: ${db.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    generate-ddl: true

#jpa log
logging:
  level:
    org:
      hibernate:
        orm.jdbc.bind: trace # 3??
        sql: debug
        type:
          descriptor.sql: trace # 2??

# aws
cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
      upload:
        profile:
          image-url: ${s3.upload.profile.image-url}
          key: ${s3.upload.profile.key}
    region:
      static: ap-northeast-2
    stack:
      auto: false

    # IAM
    credentials:
      access-key: ${s3.iam.access-key}
      secret-key: ${s3.iam.secret-key}